config/routes.rb
Rails.application.routes.draw do

  # Root
  root        'welcome#index'

  # Devise
  devise_for  :users

  # Articles
  get         'wiki/:title',        controller: :articles, action: :show, constraints: {title: /.*/}
  post        'articles/preview',   controller: :articles, action: :preview
  resources   :articles, only: ['new', 'create', 'edit', 'update']

  # Tags
  get         'tags/:name/articles', controller: :tags, action: :articles, constraints: {name: /.*/}
  resources   :tags, only: ['index', 'new', 'create', 'edit', 'update', 'destroy']

  # Not found
  get '*path', controller: 'application', action: 'error_404'

end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <strong><%= link_to "My Wiki", root_url, class: "navbar-brand" %></strong>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<%= params[:controller] == 'tags' ? 'active' : '' %>">
                    <%= link_to 'Tags', tags_url %>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <% if user_signed_in? %>
                    <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.login_id %> <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li role="presentation">
                            <%= link_to('Profile', edit_user_registration_url, role: 'menuitem', tabindex: '-1') %>
                        </li>
                        <li role="presentation">
                            <%= link_to('New article', new_article_url, role: 'menuitem', tabindex: '-1') %>
                        </li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation">
                            <%= link_to('Logout', destroy_user_session_url, role: 'menuitem', tabindex: '-1') %>
                        </li>
                    </ul>
                <% else %>
                    <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Guest <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li role="presentation">
                            <%= link_to('Sign up', new_user_registration_url, role: 'menuitem', tabindex: '-1') %>
                        </li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation">
                            <%= link_to('Login', new_user_session_url, role: 'menuitem', tabindex: '-1') %>
                        </li>
                    </ul>
                <% end %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Wiki</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/navigation' %>
<div id='container' class='container'>
    <%= yield %>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>
</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Keywords</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "My Wiki", root_url, class: "navbar-brand" %>
    </div>
  </div>
</div>
<div id='container' class='container'>
  <%= yield %>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
</body>
</html>